spring:
  application:
    name: movies-front
  messages:
    basename: messages
    encoding: ISO-8859-15

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

base:
  url: /api/movie-finder